############################################################################
#
#  Program:  OpenSees
#
#  Purpose:  A Top-level Makefile to create the libraries needed
#	     to use the OpenSees framework. Works on Linux version 6.1
#            and below.
#
#  Written: fmk
#  Created: 10/99
#
#  Send bug reports, comments or suggestions to fmckenna@ce.berkeley.edu
#
############################################################################

# %---------------------------------%
# |  SECTION 1: PROGRAM             |
# %---------------------------------%
#
# Specify the location and name of the OpenSees interpreter program
# that will be created (if this all works!)

opensees_dir = /Users/yiz/Work/OpenSeesLite
opensees_libpath = $(opensees_dir)/lib

OpenSees_PROGRAM = $(opensees_dir)/bin/OpenSees
PROGRAMMING_MODE = SEQUENTIAL

ifeq ($(PROGRAMMING_MODE), PARALLEL_INTERPRETERS)
    PROGRAMMING_FLAG = -D_PARALLEL_INTERPRETERS
endif

ifeq ($(PROGRAMMING_MODE), PARALLEL)
    PROGRAMMING_FLAG = -D_PARALLEL_PROCESSING
endif

OPERATING_SYSTEM = LINUX

#GRAPHICS = UsingOpenGL
#GRAPHIC_FLAG = -D_GLX
GRAPHICS = NONE
GRAPHIC_FLAG = -D_NOGRAPHICS


#DEBUG_MODE = DEBUG
DEBUG_MODE = NO_DEBUG
#DEBUG_FLAG = -D_G3DEBUG

#RELIABILITY = NO_RELIABILITY
RELIABILITY = YES_RELIABILITY
RELIABILITY_FLAG = -D_RELIABILITY

# PFEM_FLAG = -D_PFEM -fopenmp
PFEM_FLAG =

ifeq ($(PROGRAMMING_MODE), SEQUENTIAL)
    MUMPS_FLAG =
    HAVEMUMPS =
    MUMPS =

else
    MUMPS_FLAG = -D_MUMPS
    HAVEMUMPS = YES
    MUMPS = YES

#PETSC_FLAG =  -D_PETSC
    PETSC_FLAG =
    #HAVEPETSC = YES
    #PETSC = YES
endif

# %---------------------------------%
# |  SECTION 2: PATHS               |
# %---------------------------------%
#
# Note: if vendor supplied BLAS and LAPACK libraries or if you have
# any of the libraries already leave the directory location blank AND
# remove the directory from DIRS.

FE		= $(opensees_dir)/SRC

BLASdir      = $(opensees_dir)/OTHER/BLAS
CBLASdir     = $(opensees_dir)/OTHER/CBLAS
LAPACKdir    = $(opensees_dir)/OTHER/LAPACK
SUPERLUdir   = $(opensees_dir)/OTHER/SuperLU_5.1.1/SRC
ARPACKdir    = $(opensees_dir)/OTHER/ARPACK
UMFPACKdir   = $(opensees_dir)/OTHER/UMFPACK
ITPACKdir   = $(opensees_dir)/OTHER/ITPACK
AMDdir       = $(opensees_dir)/OTHER/AMD
CSPARSEdir   = $(opensees_dir)/OTHER/CSPARSE
#TRIANGLEdir   = $(opensees_dir)/OTHER/Triangle
#TETGENdir   = $(opensees_dir)/OTHER/tetgen1.5.0
SRCdir       = $(opensees_dir)/SRC

ifeq ($(PROGRAMMING_MODE), SEQUENTIAL)
    SUPERLU_DISTdir =
    SUPERLU_INCLUDES =
    METISdir       =
else
    SUPERLU_DISTdir = $(opensees_dir)/OTHER/SuperLU_DIST_4.3/SRC
    SUPERLU_INCLUDES = -I$(SUPERLU_DISTdir)
    METISdir       = $(opensees_dir)/OTHER/METIS
endif

DIRS    = $(BLASdir) $(CBLASdir) $(LAPACKdir) $(ITPACKdir) $(SUPERLUdir) $(ARPACKdir) $(UMFPACKdir) $(SRCdir) $(METISdir) $(AMDdir) $(CSPARSEdir) $(SUPERLU_DISTdir)


# %-------------------------------------------------------%
# | SECTION 3: LIBRARIES                                  |
# |                                                       |
# | The following section defines the libraries that will |
# | be created and/or linked with when the libraries are  |
# | being created or linked with.                         |
# %-------------------------------------------------------%
#
# Note: if vendor supplied BLAS and LAPACK libraries leave the
# libraries blank. You have to get your own copy of the tcl/tk
# library!!
#
# Note: For libraries that will be created (any in DIRS above)
# make sure the directory exsists where you want the library to go!

FE_LIBRARY      = $(opensees_libpath)/libOpenSees.a
NDARRAY_LIBRARY = $(opensees_libpath)/libndarray.a # BJ_UCD jeremic@ucdavis.edu
MATMOD_LIBRARY  = $(opensees_libpath)/libmatmod.a  # BJ_UCD jeremic@ucdavis.edu
BJMISC_LIBRARY  = $(opensees_libpath)/libBJmisc.a  # BJ_UCD jeremic@ucdavis.edu
LAPACK_LIBRARY  = $(opensees_libpath)/libLapack.a
BLAS_LIBRARY    = $(opensees_libpath)/libBlas.a
SUPERLU_LIBRARY = $(opensees_libpath)/libSuperLU.a
CBLAS_LIBRARY   = $(opensees_libpath)/libCBlas.a
ARPACK_LIBRARY  = $(opensees_libpath)/libArpack.a
UMFPACK_LIBRARY = $(opensees_libpath)/libUmfpack.a
ITPACK_LIBRARY = $(opensees_libpath)/libItpack.a
AMD_LIBRARY     = $(opensees_libpath)/libAMD.a
CSPARSE_LIBRARY = $(opensees_libpath)/libcsparse.a
#TRIANGLE_LIBRARY = $(opensees_libpath)/libTriangle.a
#TETGEN_LIBRARY = $(opensees_libpath)/libTetgen.a
RELIABILITY_LIBRARY = $(opensees_libpath)/libReliability.a
OPTIMIZATION_LIBRARY = $(opensees_libpath)/libOptimization.a
GFORTRAN_LIBRARY = /usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/libgfortran.a
OMP_LIBRARY = /usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/libgomp.dylib
GCC_LIBRARY = /usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin16.7.0/7.3.0/libgcc.a
QUADMATH_LIBRARY = /usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/libquadmath.a

ifeq ($(PROGRAMMING_MODE), SEQUENTIAL)
    DISTRIBUTED_SUPERLU_LIBRARY =
    METIS_LIBRARY   =
else
    DISTRIBUTED_SUPERLU_LIBRARY = $(opensees_libpath)/libDistributedSuperLU.a
    METIS_LIBRARY   = $(opensees_libpath)/libMetis.a
endif

TCL_LIBRARY = 

#GRAPHIC_LIBRARY     = -lGL -lGLU -lXft -lXrender

# WATCH OUT .. These libraries are removed when 'make wipe' is invoked.
WIPE_LIBS	= $(FE_LIBRARY) \
		$(LAPACK_LIBRARY) \
		$(BLAS_LIBRARY) \
		$(CBLAS_LIBRARY) \
		$(SUPERLU_LIBRARY) \
                $(DISTRIBUTED_SUPERLU_LIBRARY) \
		$(ARPACK_LIBRARY) \
		$(UMFPACK_LIBRARY) \
		$(ITPACK_LIBRARY) \
	        $(METIS_LIBRARY) \
	        $(AMD_LIBRARY) \
	        $(CSPARSE_LIBRARY) \
		$(TRIANGLE_LIBRARY) \
		$(TETGEN_LIBRARY) \
		$(RELIABILITY_LIBRARY)\
		$(OPTIMIZATION_LIBRARY)

# %---------------------------------------------------------%
# | SECTION 4: COMPILERS                                    |
# |                                                         |
# | The following macros specify compilers, linker/loaders, |
# | the archiver, and their options.  You need to make sure |
# | these are correct for your system.                      |
# %---------------------------------------------------------%

# Compilers


ifeq ($(PROGRAMMING_MODE), SEQUENTIAL)

MPI_BIN =
MPI_INCLUDE =
MPI_LIB =

CC++	= clang++
CC      = clang
FC	= /usr/local/Cellar/gcc/7.3.0_1/bin/gfortran
#NVCC    = /usr/local/apps/cuda/cuda-7.5.18/bin/nvcc

else

MPI_BIN = $(mpidir)/bin
MPI_INCLUDE = -I$(mpidir)/include
MPI_LIB = $(mpidir)/lib
#NVCC    = /usr/local/apps/cuda/cuda-7.5.18/bin/nvcc

CC++            =  $(MPI_BIN)/mpicxx
CC              =  $(MPI_BIN)/mpicc
FC              =  $(MPI_BIN)/mpif90
F90             =  $(MPI_BIN)/mpif90
FORTRAN             =  $(FC)

endif

AR		= ar
ARFLAGS		= cqls
RANLIB		= ranlib
RANLIBFLAGS     =

# Compiler Flags
#
# NOTES:
#    C++ FLAGS TAKE need _UNIX or _WIN32 for preprocessor dircetives
#         - the _WIN32 for the Windows95/98 or NT operating system.
#    C FLAGS used -DUSE_VENDOR_BLAS (needed in SuperLU) if UNIX in C++ FLAGS
#

# modified as optimizaton currently causing problems with Steeln01 code
ifeq ($(DEBUG_MODE), DEBUG)

opensees_C++FLAGS = -Wall -D_LINUX -D_UNIX  -D_TCL85 $(GRAPHIC_FLAG) $(RELIABILITY_FLAG) $(DEBUG_FLAG) $(PROGRAMMING_FLAG) -D_COROTATIONAL -g -pg $(MUMPS_FLAG) $(PETSC_FLAG) -fPIC
CFLAGS          = -Wall -pg $(GRAPHIC_FLAG) $(RELIABILITY_FLAG) $(DEBUG_FLAG) $(PROGRAMMING_FLAG) $(PFEM_FLAG) -fPIC -std=c99
FFLAGS          = -Wall -fPIC

# Linker
LINKER          = $(CC++)
# LINKFLAGS       = -g -pg
LINKFLAGS       =

else
opensees_C++FLAGS  = -Wall -D_LINUX -D_UNIX -D_TCL85 $(GRAPHIC_FLAG) $(RELIABILITY_FLAG) $(DEBUG_FLAG) $(PROGRAMMING_FLAG) -O3 -ffloat-store -D_COROTATIONAL $(PFEM_FLAG) $(MUMPS_FLAG) $(PETSC_FLAG) -fPIC
CFLAGS          = -Wall -O2 $(PFEM_FLAG) -fPIC -ansi
FFLAGS          = -Wall -O -fPIC

# Linker
LINKER          = $(CC++)
#LINKFLAGS       = -rdynamic -Wl
LINKFLAGS =
endif


# Misc
MAKE		= make
CD              = cd
ECHO            = echo
RM              = rm
RMFLAGS         = -f
SHELL           = /bin/sh

# %---------------------------------------------------------%
# | SECTION 5: COMPILATION                                  |
# |                                                         |
# | The following macros specify the macros used in         |
# | to compile the source code into object code.            |
# %---------------------------------------------------------%

.SUFFIXES:
.SUFFIXES:	.C .c .f .f90 .cpp .o .cpp

#
# %------------------%
# | Default command. |
# %------------------%
#
.DEFAULT:
	@$(ECHO) "Unknown target $@, try:  make help"
#
# %-------------------------------------------%
# |  Command to build .o files from .f files. |
# %-------------------------------------------%
#

.cpp.o:
	@$(ECHO) Making $@ from $<
	$(CC++) $(opensees_C++FLAGS) $(opensees_INCLUDES) -c $(shell pwd)/$< -o $(shell pwd)/$@

.C.o:
	@$(ECHO) Making $@ from $<
	$(CC++) $(opensees_C++FLAGS) $(opensees_INCLUDES) -c $(shell pwd)/$< -o $(shell pwd)/$@
.c.o:
	@$(ECHO) Making $@ from $<
	$(CC) $(CFLAGS) -c $(shell pwd)/$< -o $(shell pwd)/$@
.f.o:
	@$(ECHO) Making $@ from $<
	$(FC) $(FFLAGS) -c $(shell pwd)/$< -o $(shell pwd)/$@

# %---------------------------------------------------------%
# | SECTION 6: OTHER LIBRARIES                              |
# |                                                         |
# | The following macros specify other libraries that must  |
# | be linked with when creating executables. These are     |
# | platform specific and typically order does matter!!     |
# %---------------------------------------------------------%

ifeq ($(PROGRAMMING_MODE), SEQUENTIAL)

MUMPS_LIB =
MUMPS_INCLUDE =

PETSC_LIB =
PETSC_INCLUDE =

else

MUMPS_LIB = -L$(mumpsdir)/lib \
          -L$(scalapackdir)/lib \
	$(FE)/system_of_eqn/linearSOE/mumps/MumpsSOE.o \
	$(FE)/system_of_eqn/linearSOE/mumps/MumpsSolver.o \
	$(FE)/system_of_eqn/linearSOE/mumps/MumpsParallelSOE.o \
	$(FE)/system_of_eqn/linearSOE/mumps/MumpsParallelSolver.o \
	-ldmumps -lmumps_common \
	-lpord -lscalapack -lblas -llapack
MUMPS_INCLUDE = -I$(mumpsdir)/include

#PETSC_LIB = -L$(petscdir)/lib -lpetsc
#PETSC_INCLUDE = -I$(petscdir)/../include

OTHER_PARA_LIB =  -lparmetis -lmetis -lmpi -lmpicxx -lmpifort

endif

MACHINE_LINKLIBS  =  -L/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin16.7.0/7.3.0

MACHINE_NUMERICAL_LIBS  = $(RELIABILITY_LIBRARY) $(OPTIMIZATION_LIBRARY) -lm \
		$(QUADMATH_LIBRARY) \
		$(GCC_LIBRARY) \
		$(OMP_LIBRARY) \
		$(GFORTRAN_LIBRARY) \
		$(ARPACK_LIBRARY) \
		$(SUPERLU_LIBRARY) \
		$(UMFPACK_LIBRARY) \
                $(DISTRIBUTED_SUPERLU_LIBRARY) \
                $(METIS_LIBRARY) \
		$(ITPACK_LIBRARY) \
		$(AMD_LIBRARY) \
		$(CSPARSE_LIBRARY) \
		$(TRIANGLE_LIBRARY) \
		$(TETGEN_LIBRARY) \
		$(LAPACK_LIBRARY) $(BLAS_LIBRARY) $(CBLAS_LIBRARY) \
		$(GRAPHIC_LIBRARY) \
		-ldl -lpng -lssl
		#-L/usr/local/apps/cuda/cuda-7.5.18/lib64 -lcusolver -lcudart -lcusparse

MACHINE_SPECIFIC_LIBS =

PARALLEL_LIB = $(MUMPS_LIB) -L$(MPI_LIB) $(OTHER_PARA_LIB) $(PETSC_LIB)

# %---------------------------------------------------------%
# | SECTION 7: INCLUDE FILES                                |
# |                                                         |
# | The following macros specify include files needed for   |
# | compilation.                                            |
# %---------------------------------------------------------%
MACHINE_INCLUDES        = -I/usr/include \
			  -I/usr/local/include \
			  -I/usr/include/cxx  
#			  -I/scratch/bin/anaconda3/include/python3.6m
#			  -I/usr/include/python2.7
#			  -I/usr/local/apps/cuda/cuda-7.5.18/include


# this file contains all the OpenSees/SRC includes
include $(FE)/Makefile.incl

TCL_INCLUDES = -I/usr/include

opensees_INCLUDES = $(TCL_INCLUDES) $(FE_INCLUDES) $(MACHINE_INCLUDES) $(SUPERLU_INCLUDES) $(MUMPS_INCLUDE) $(MPI_INCLUDE) $(PETSC_INCLUDE)
